language: node_js
node_js:
  - lts/*
before_script:
  - npm install -g typescript
script:
  - tsc
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
  - stryker run --reporters dashboard
branches:
  only:
    - v2
    - /^v2-.*$/